/* DO NOT EDIT THIS FILE - it is machine generated */
/*
 * judge.h
 *
 *  Created on: 2017年5月1日
 *      Author: mozre
 */

#include <jni.h>
#include <string.h>
#include "judge.h"
/* Header for class com_thinkgem_jeesite_modules_judge_JudgeC */

#ifndef _Included_com_thinkgem_jeesite_modules_judge_JudgeC
#define _Included_com_thinkgem_jeesite_modules_judge_JudgeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thinkgem_jeesite_modules_judge_JudgeC
 * Method:    startJudge
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_thinkgem_jeesite_modules_judge_JudgeC_startJudge(
		JNIEnv * env, jobject obj, jstring jpath, jobjectArray args,
		jstring jresult);

#ifdef __cplusplus
}
#endif
#endif
